### ISSUE TITLE
Design the Hero Section with Simple Text and Background

### ISSUE THREAD

**Issue by arshad-khan1** [arshad-khan1/SimpleNikeWebsite#10]
Create a hero section with a “**#28282B**” background, 
My Name: “ARSHAD KHAN” in Capital Letters. (Color: “**#FFFFFF**”)
and a short tagline: “Software Developer”. (Color: “**#e8e8e8**”)

Text should be on the center of the screen.

**Comment by keshav-09** [comment]
Hi @arshad-khan1 
I would like to work on this task. Could you please reply so that I can start my work?

**Comment by arshad-khan1** [comment]
Hi @keshav-09,
Thanks for your time. Please start working on the task.
Please feel free to ask queries if you have any.

**Comment by keshav-09** [comment]
I have just two question: What should be the font size?
Also, should both texts have the same font size?

**Comment by arshad-khan1** [comment]
"Arshad Khan" should be bigger than "Software Developer".
Please do some try and keep the one appears best.
"Arshad Khan" should be nearly 200px.

**Comment by keshav-09** [comment]
okay,
I will raise the PR and let you know.

Thank you!

**Comment by arshad-khan1** [comment]
Hi @keshav-09,
Thanks for completing the task as required
