### ISSUE TITLE
Create the About Section with Image and skills

### ISSUE THREAD

**Issue by arshad-khan1** [arshad-khan1/SimpleNikeWebsite#11]
Write the code under “#About Section” comment. Do the designing in style.css under “#About Section”

Design a two-column layout for the About section:

- **Left Column (40% width):**
    - Add a professional photo
    - Image dimensions: 400x400px
    - Rounded corners (border-radius: 8px)
    - Light shadow effect
- **Right Column (60% width):**
    - Brief introduction paragraph
    - Skills section with flex-wrap cards
    - Each skill card should:
    • Have consistent width (150px)
    • Include an icon
    • Show skill name
    • Have rounded corners

**Layout Requirements:**

- Use flexbox for main container
- Add proper spacing between elements

**Content:**

- **Brief Introduction:** Hi, I'm **Arshad Khan**, a passionate **full-stack developer** with expertise in the **MERN stack**, **Java**, and **SQL**. I specialize in building dynamic, user-friendly web applications and have a knack for blending creativity and technology to deliver impactful solutions.
- **Skills:** MERN, Java, MySQL, AWS. Add images of the respective Technology in the cards.
![About](https://github.com/user-attachments/assets/dd7eb534-fc3a-4f16-be3e-660a2e1e0b17)

**Comment by kambleaishwarya** [comment]
hi, im interested to take up this issue.

**Comment by arshad-khan1** [comment]
Hi @kambleaishwarya, 
You can work on this issue. 
Please feel to ask any question if you have.

**Comment by kambleaishwarya** [comment]
- Can you please send me the links to the images that I need to add?

**Comment by arshad-khan1** [comment]
I have attach Google drive link. Please download image from this link.
Link: https://drive.google.com/file/d/1fTFaTtuSHh5kjRRVR5MZsA6s2W_-_1Gk/view?usp=drive_link

**Comment by kambleaishwarya** [comment]
okay
please give me permission to access images from your drive.
i have sent you request.

**Comment by kambleaishwarya** [comment]
- Hii arshad i have raised a pull request please check once.

**Comment by arshad-khan1** [comment]
@kambleaishwarya, Thank you for completing the task as per the requirement
Closing this issue
