### ISSUE TITLE
Add the Projects Section having three project cards 

### ISSUE THREAD

**Issue by arshad-khan1** [arshad-khan1/SimpleNikeWebsite#12]
Create three projects card with project description and image. Card should be redirecting to a link.

Write the code under “#Project Section” comment

Use style.css to style the card. (Card Color: “**Dark Grey**”)

**Content:**

- Project 1
    - Description: A webapp to get all the informations about latest movies.
    - Image: https://drive.google.com/file/d/1C9QXycbVPp50ouzMo_wtYgvygGavDBDt/view?usp=drive_link
    - Link: https://moviehub-react-project-4vrq47tnv-arshad-khans-projects-94cea73b.vercel.app/
- Project 2
    - Description: A webapp to visualize how different sorting algorithms work
    - Image: https://drive.google.com/file/d/15xNeFx3UpAyDcJrqTknWdl5XRByAYnY3/view?usp=drive_link
    - Link: https://sorting-visualizer-do75b4jjj-arshad-khans-projects-94cea73b.vercel.app/
- Project 3
    - Description: A Frontend clone of Digital Marketing Website.
    - Image: https://drive.google.com/file/d/1KbgpQYUzMhMxfRu3qAAgmHTp2ZJf-729/view?usp=drive_link
    - Link: https://arshad-khan1.github.io/Obys_Clone/
  
![Project](https://github.com/user-attachments/assets/84e8eaa3-73d5-4e0d-a224-8e972909af1e)

**Comment by Saifkhan-rkp** [comment]
Hey @arshad-khan1  I am interested in working on this issue. I have been sent a request to access request to above attached drive link. please grant access request, so I start work further. it seems authentication requires to each vercel link?

**Comment by arshad-khan1** [comment]
Hi @Saifkhan-rkp, you can start woking on this issue.
I will give you access to the image links. Please download them in assets folder and include it in the html code.
For vercel, the visitor have to login using their account to access the web page. You don't have to worry about that.

**Comment by Saifkhan-rkp** [comment]
@arshad-khan1  thanks..

**Comment by Saifkhan-rkp** [comment]
Hey @arshad-khan1 I'll be using `assets/images` folder for images of project. is it okay ?

**Comment by arshad-khan1** [comment]
@Saifkhan-rkp Sure you can use `assets/images`. 
I have given you access to the images.

Please let me know if you have any more doubts.

**Comment by Saifkhan-rkp** [comment]
@arshad-khan1 I have created PR for this issue, please review PR #22 and suggests the changes if any.

**Comment by arshad-khan1** [comment]
I have checked and merged your code.

Thanks for helping me out @Saifkhan-rkp,
Loved your work
Thanks again
