### ISSUE TITLE
Add Footer Section with social media icons

### ISSUE THREAD

**Issue by arshad-khan1** [arshad-khan1/SimpleNikeWebsite#13]
At the end of the index.html file, write code for Footer with:

- Background Color:
- Text on left: “Arshad Khan”
- Email ID on center: “003arshad@gmail.com”
- Social media icons on right: Instagram, LinkedIn, Github. (Icons should be clickable for redirection).

For reference:
![footer](https://github.com/user-attachments/assets/f6ac5eab-65fa-4eea-bc04-e21932eed227)

**Comment by shubham-ghaturle01** [comment]
Hi @arshad-khan1 ,

I would like to add a footer to the index.html file with the following details:

Name: "Arshad Khan"
Email: "003arshad@gmail.com" (clickable link)
Social media icons (Instagram, LinkedIn, GitHub)
Please let me know if you're okay with this change.

**Comment by arshad-khan1** [comment]
Hi @Shubhuscode,
I would be more than happy if you help me with this.
Please start working on it and ask any queries if you get at any point of time.
Thanks

**Comment by arshad-khan1** [comment]
Thanks @Shubhuscode.

**Comment by arshad-khan1** [comment]
This Issue has been resolved by @Shubhuscode
