### ISSUE TITLE
Integrate Social Media Links to the footer

### ISSUE THREAD

**Issue by arshad-khan1** [arshad-khan1/SimpleNikeWebsite#14]
In the footer section code in index.html, add the the links to the respective social media icon.

- Instagram: [https://www.instagram.com/arshad_khan0307](https://www.instagram.com/arshad_khan0307/#)
- LinkedIn: https://www.linkedin.com/in/arshad-khan-linkdin/
- Github: https://github.com/arshad-khan1

Link should open in new tab.

**Comment by shubham-ghaturle01** [comment]
Hi @arshad-khan1 , may I have your permission to add social media links (Instagram, LinkedIn, GitHub) to the footer in index.html?

**Comment by arshad-khan1** [comment]
Hi @Shubhuscode,
Once the #13 issue is solved, you can start working on this.
Thanks for taking your time and helping me out.
