### ISSUE TITLE
Delete Existing Files and set up Basic File Structure 

### ISSUE THREAD

**Issue by arshad-khan1** [arshad-khan1/SimpleNikeWebsite#7]
Remove all existing files from the current repository except [README.md] to prepare for the portfolio website.

After that,

**Create Files:**
- index.html
- style.css
- In both files, write comments:
    - “Navbar Section”
    - “Hero Section”
    - “About Section”
    - “Project Section”
    - “Contact Section”
    - “Footer Section”
- Link style.css file in index.html
- In style.css, add code for:
```
@import url("https://fonts.googleapis.com/css2?family=Fjalla+One&family=Open+Sans:ital,wght@0,300..800;1,300..800&family=Rubik+Mono+One&family=Staatliches&display=swap");

body {
  background-color: #28282b;
  color: #e8e8e8;
  padding: 0px 40px;
  font-family: "Fjalla One", serif;
}
```

**Create Folder:**
- assets/

**Comment by keshav-09** [comment]
Hi @arshad-khan1,

I just checked out on your issues and I can help you with this.

Please let me know if I someone else is on this task or can I proceed with it.

Thank you,
Keshav

**Comment by arshad-khan1** [comment]
Hi @keshav-09,

Thank you for showing interest on my project.

You can proceed with the task.

Thank you,
Arshad

**Comment by keshav-09** [comment]
Thank  you @arshad-khan1. 
I will complete the task and create the PR.

**Comment by arshad-khan1** [comment]
Thank you @keshav-09 for taking time and completing the task.
