### ISSUE TITLE
Change Website Title and Logo in the Header

### ISSUE THREAD

**Issue by arshad-khan1** [arshad-khan1/SimpleNikeWebsite#8]
In the index.html file:

- change the title tag to **“Arshad - Portfolio”**
- change logo by adding **<link>** tag.
- Logo SVG:
`<svg xmlns="http://www.w3.org/2000/svg" xml:space="preserve" width="24" height="24" id="logo">
<path d="M12 1.8c-3 0-5.4 2.4-5.4 5.4S9 12.6 12 12.6s5.4-2.4 5.4-5.4S15 1.8 12 1.8zm0 7.8c-1.3 0-2.4-1.1-2.4-2.4s1.1-2.4 2.4-2.4 2.4 1.1 2.4 2.4-1.1 2.4-2.4 2.4z"></path>
<path d="M12 18.6c.1 0 .3 0 .4.1l3 3c.6.6 1.6.6 2.1 0 .6-.6.6-1.5 0-2.1l-1.8-1.8c-.1-.1-.2-.3-.1-.5 0-.2.1-.3.3-.4 1.3-.5 2.5-1.3 3.5-2.3.3-.3.4-.7.4-1.1s-.2-.8-.4-1.1c-.6-.6-1.6-.6-2.1 0-1.5 1.6-3.3 2.4-5.3 2.4s-3.8-.8-5.2-2.2c-.6-.6-1.6-.6-2.1 0-.6.6-.6 1.5 0 2.1 1 1 2.2 1.8 3.5 2.3.2.1.3.2.3.4s0 .3-.1.5l-1.8 1.8c-.6.6-.6 1.5 0 2.1.6.6 1.6.6 2.1 0l3-3c0-.1.2-.2.3-.2z"></path>
</svg>`

**Comment by shubham-ghaturle01** [comment]
Hi @arshad-khan1 ,

I hope you're doing well. I have noticed a few updates that can improve the portfolio website, and I would like to make the following changes:

Title Update: Change the title of the webpage to "Arshad - Portfolio".
Logo Update: Replace the current logo with a new SVG logo (which I have included below).
Here's the SVG logo to be used:

<svg xmlns="http://www.w3.org/2000/svg" xml:space="preserve" width="24" height="24" id="logo">
  <path d="M12 1.8c-3 0-5.4 2.4-5.4 5.4S9 12.6 12 12.6s5.4-2.4 5.4-5.4S15 1.8 12 1.8zm0 7.8c-1.3 0-2.4-1.1-2.4-2.4s1.1-2.4 2.4-2.4 2.4 1.1 2.4 2.4-1.1 2.4-2.4 2.4z"></path>
  <path d="M12 18.6c.1 0 .3 0 .4.1l3 3c.6.6 1.6.6 2.1 0 .6-.6.6-1.5 0-2.1l-1.8-1.8c-.1-.1-.2-.3-.1-.5 0-.2.1-.3.3-.4 1.3-.5 2.5-1.3 3.5-2.3.3-.3.4-.7.4-1.1s-.2-.8-.4-1.1c-.6-.6-1.6-.6-2.1 0-1.5 1.6-3.3 2.4-5.3 2.4s-3.8-.8-5.2-2.2c-.6-.6-1.6-.6-2.1 0-.6.6-.6 1.5 0 2.1 1 1 2.2 1.8 3.5 2.3.2.1.3.2.3.4s0 .3-.1.5l-1.8 1.8c-.6.6-.6 1.5 0 2.1.6.6 1.6.6 2.1 0l3-3c0-.1.2-.2.3-.2z"></path>
</svg>

Would it be okay for me to go ahead and implement these changes?

Please let me know if you approve of these updates or if you'd like to discuss them further.

Thank you!
Shubham Ghaturle

**Comment by arshad-khan1** [comment]
Hi @Shubhuscode,

Thank you for your time. Please go ahead with implementing these changes.

Please let me know if you have any doubts regarding the task.

Thank You

**Comment by shubham-ghaturle01** [comment]
Hi @arshad-khan1,

I’ve made the requested changes, but I encountered an issue with adding the SVG logo. It seems that the SVG tag isn't being accepted or rendered properly.

Would you like me to try an alternative format for the logo (e.g., PNG or JPEG), or would you prefer a different approach? Let me know how you'd like to proceed.

**Comment by arshad-khan1** [comment]
I am sending you link for that image.
Please download this logo image in the assets/images
Link: https://drive.google.com/file/d/1KIHjHkNKub95u8AWxfOKOA37cCE9LqlK/view?usp=sharing

**Comment by shubham-ghaturle01** [comment]
OKAY

**Comment by arshad-khan1** [comment]
Thanks @Shubhuscode
