### ISSUE TITLE
Implement Navbar Code on Home page

### ISSUE THREAD

**Issue by arshad-khan1** [arshad-khan1/SimpleNikeWebsite#9]
Create a navigation bar with links to Home, About, Projects, and Contact sections. It should be at the center of the navbar.

**Height:** 80vh
**Width:** 100%

Color:

- Background: **#28282B**
- Text Color: **#e8e8e8**
- Text bold

For Reference:
![navbar](https://github.com/user-attachments/assets/d1c014b5-fba9-4b2a-b3e6-11164a413a87)

**Comment by MuktaTiwari** [comment]
Hii @arshad-khan1 
I would like to handle these things, so can I do it?

**Comment by arshad-khan1** [comment]
Hi @MuktaTiwari,
Please go ahead with making the change and feel free to ask any queries while working on it.
Thank you

**Comment by arshad-khan1** [comment]
Thanks @MuktaTiwari for completing the task as asked.
